#!/bin/sh

# на сервере qsoftbk@144.76.28.102 создаем каталог, где будут хранится скрипт и бекапы
#mkdir /mnt/qsoftbk/backup

#делаем бекап каталогов из сервера, откуда будем делать бекапы (file) на сервер куда будут идти бекапы (qsoft-bak)
#бекап архивов баз данных
cd /home/backups/databases; tar -cvz . | ssh qsoftbk@144.76.28.102 'cat > /mnt/qsoftbk/backup/databases$(date +"%Y-%m-%d").tar.gz' 

#бекап боевых сайтов
cd /home/backups/files/external; tar -cvz . | ssh qsoftbk@144.76.28.102 'cat > /mnt/qsoftbk/backup/external$(date +"%Y-%m-%d").tar.gz'

#бекап внутренних сервисов
cd /home/backups/files/qsoft; tar -cvz . | ssh qsoftbk@144.76.28.102 'cat > /mnt/qsoftbk/backup/files_qsoft$(date +"%Y-%m-%d").tar.gz'
cd /home/backups/other/qsoft; tar -cvz . | ssh qsoftbk@144.76.28.102 'cat > /mnt/qsoftbk/backup/other_qsoft$(date +"%Y-%m-%d").tar.gz'

#удаляем резервные копии старше 5 дней
ssh qsoftbk@144.76.28.102 "find ./backups -mtime +5 -print -delete"

#бекап называю backup.sh. Потом меняю права chmod u+x backup.sh
#в кроне добавляю строчку в /etc/crontab на серваке qsoft@files.crt
# minute hour mday month wday who         command
#  0      02   *    *     *    qsoftbk /home/backups/backup.sh
