#!/bin/sh

#создаем каталоги, где будут хранится скрипт и бекапы
mkdir /mnt/qsoftbk/backup
mkdir /mnt.qsoft/backup/backups

#переходим в каталог, где лежит скрипт
cd /mnt/qsoftbk/backup

#делаем бекап каталогов из сервера, откуда будем делать бекапы (file) на сервер куда будут идти бекапы (qsoft-bak)
#бекап архивов баз данных
ssh qsoftbk@file "tar cvzf - /home/backups/databases/* > ./backups/databases-`date "+%Y-%m-%d"`.tgz
#бекап сайтов боевых
ssh qsoftbk@file "tar cvzf - /home/backups/files/external/* > ./backups/external-`date "+%Y-%m-%d"`.tgz
#бекап внутренних сервисов
ssh qsoftbk@file "tar cvzf - /home/backups/files/qsoft/* > ./backups/files_qsoft-`date "+%Y-%m-%d"`.tgz
ssh qsoftbk@file "tar cvzf - /home/backups/other/qsoft/* > ./backups/other_qsoft-`date "+%Y-%m-%d"`.tgz

#удаляем резервные копии старше 5 дней
find ./backups -mtime +5 -print -delete

#бекап называю backup.sh. Потом меняю права chmod u+x backup.sh
#в кроне добавляю строчку в /etc/crontab на серваке qsoft-bak где будут храниться бекапы
# minute hour mday month wday who         command
  0      02   *    *     *    qsoftbk /mnt/qsoftbk/backup/daily-backup.sh
